# -*- coding: utf-8 -*-
"""home assignement 4 ml coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxdBtwPxtRi3uD2hMzNwOivxTKpEfS9U

question 1
"""

import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

text = "John enjoys playing football while Mary loves reading books in the library."

# Process the text
doc = nlp(text)

# Tokenize, remove stopwords, lemmatize, and filter for Verbs and Nouns
cleaned_tokens = [
    token.lemma_ for token in doc
    if not token.is_stop and token.pos_ in ["VERB", "NOUN"]
]

print(cleaned_tokens)

"""question 2"""

input_text = "Chris met Alex at Apple headquarters in California. He told him about the new iPhone launch."

doc = nlp(input_text)

# 1. Named Entity Recognition
print("Entities Found:")
for ent in doc.ents:
    print(f"{ent.text} ({ent.label_})")

# 2. Disambiguation Check
pronouns = ["he", "she", "they"]
# Check if any token's lower-case text is in our pronoun list
if any(token.lower_ in pronouns for token in doc):
    print("\nWarning: Possible pronoun ambiguity detected!")